LambdaForums/Models/Search/SearchResultModel.cs
using LambdaForums.Models.Post;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LambdaForums.Models.Search
{
    public class SearchResultModel
    {
        public IEnumerable<PostListingModel> posts { get; set; }
        public string SeachQuery { get; set; }
        public bool EmptySearchResults { get; set; }
    }
}

LambdaForums/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LambdaForums.Data;
using LambdaForums.Models.Forum;
using LambdaForums.Models.Post;
using LambdaForums.Data.Models;

namespace LambdaForums.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum _forumService;
        private readonly IPost _postService;

        public ForumController(IForum forumService, IPost postService)
        {
            _forumService = forumService;
            _postService = postService;
        }

        public IActionResult Index()
        {
            var forums = _forumService.GetAll().Select(forum => new ForumListingModel {
                Id = forum.Id,
                Name = forum.Title,
                Desciption = forum.Description
            });

            var model = new ForumIndexModel
            {
                ForumList = forums
            };
            return View(model);
        }

        public IActionResult Topic(int id, string searchQuery)
        {
            var forums = _forumService.GetById(id);
            var posts = new List<Post>();

            posts = _postService.GetFilteredPosts(forums, searchQuery).ToList();

         

            var postListing = posts.Select(post => new PostListingModel
            {
                id = post.Id,
                AuthorId = post.User.Id,
                Author = post.User.UserName,
                AurthorRating = post.User.Rating,
                Title = post.Title,
                DatePosted = post.Created.ToString(),
                RepliesCount = post.Replies.Count(),
                Forum = BuildForumListing(post)
            });

            var model = new ForumTopicModel
            {
                Post = postListing,
                Forum = BuildForumListing(forums)
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Search(int id, string searchQuery)
        {
            return RedirectToAction("Topic", new { id, searchQuery });
        }

        private ForumListingModel BuildForumListing(Post x)
        {
            var forum = x.Forum;
            return BuildForumListing(forum);
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {
            return new ForumListingModel
            {
                Id = forum.Id,
                Name = forum.Title,
                Desciption = forum.Description,
                ImageUrl = forum.ImageUrl

            };
        }
    }
}

LambdaForums/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LambdaForums.Data.Models;
using Microsoft.AspNetCore.Identity;
using LambdaForums.Data;
using LambdaForums.Models.ApplicationUser;

namespace LambdaForums.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IApplicationUser _userService;
        private readonly IUpload _uploadService;

        public ProfileController(UserManager<ApplicationUser> userManager, IApplicationUser userService, IUpload uploadService)
        {
            _userManager = userManager;
            _userService = userService;
            _uploadService = uploadService;
        }

        public IActionResult Detail(string id)
        {
            var user = _userService.GetById(id);
            var userRoles = _userManager.GetRolesAsync(user).Result;
            var model = new ProfileModel()
            {
                UserId = user.Id,
                UserName = user.UserName,
                UserRating = user.Rating.ToString(),
                Email = user.Email,
                ProfileImgageUrl = user.ProfileImagueUrl,
                MemberSince = user.MemberSince,
                IsAdmin = userRoles.Contains("Admin")
            };
            return View(model);
        }
    }
}

LambdaForums/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LambdaForums.Data;
using LambdaForums.Models.Post;
using LambdaForums.Data.Models;
using LambdaForums.Models.Forum;
using LambdaForums.Models.Search;

namespace LambdaForums.Controllers
{
    public class SearchController : Controller
    {
        private readonly IPost _postService;

        public SearchController(IPost postService)
        {
            _postService = postService;
        }

        public IActionResult Results(string searchQuery)
        {
            var posts = _postService.GetFilteredPosts(searchQuery);

            var areNoResults = (!string.IsNullOrEmpty(searchQuery) && !posts.Any());

            var postListings = posts.Select(post => new PostListingModel
            {
                id = post.Id,
                AuthorId = post.User.Id,
                Author = post.User.UserName,
                AurthorRating = post.User.Rating,
                Title = post.Title,
                DatePosted = post.Created.ToString(),
                RepliesCount = post.Replies.Count(),
                Forum = buildForumListing(post)


                
            });

            var model = new SearchResultModel
            {
                posts = postListings,
                SeachQuery = searchQuery,
                EmptySearchResults = areNoResults
            };

            return View(model);
        }

        private ForumListingModel buildForumListing(Post post)
        {
            var forum = post.Forum;

            return new ForumListingModel
            {
                Id = forum.Id,
                ImageUrl = forum.ImageUrl,
                Name = forum.Title,
                Desciption = forum.Description

            };

        }

        [HttpPost]
        public IActionResult Search(string searchQuery)
        {
            return RedirectToAction("Results", new {searchQuery});
        }
    }
}

LambdaForums/Views/Search/Results.cshtml
@model LambdaForums.Models.Search.SearchResultModel

<div class="container body-content">
    <div class="row sectionHeader">
        <div class="sectionHeading">

            
            <span>Search Results for: @Model.SeachQuery</span>
            <form asp-controller="Search" asp-action="Search" method="post">
                <div class="searchForm">
                    <input asp-for="SeachQuery" type="text" placeholder="Search..." class="searchBar" onfocus="clearThis(this)" />
                    <button class="btn buttonSearch" type="submit">
                        <i class="material-icons"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="row forumIndexContent">
        @if (Model.posts.Any())
        {
            <table class="table table-hover table-bordered" id="searchIndexTable">
                <tbody>
                    @foreach (var post in Model.posts)
                    {
                        <tr>
                            <td>
                                <div class="forumLogo" style="background-image: url(@post.Forum.ImageUrl)">

                                </div>
                                <div class="postData">
                                    <div class="postTitle">
                                        <a asp-controller="Post" asp-action="Index" asp-route-id="@post.id">
                                            @post.Title
                                        </a>
                                    </div>
                                    <div class="forumSubTitle">
                                        <div>
                                            by:
                                            <span class="postAuthor">
                                                <a asp-controller="Profile" asp-action="Detail" asp-route-id="@post.AuthorId">
                                                    @post.Author
                                                </a>
                                                (@post.AurthorRating)
                                            </span>
                                            in: 
                                            <span class="postForum">
                                                <a asp-controller="Forum" asp-action="Topic" asp-route-id="@post.Forum.Id">
                                                    @post.Forum.Name
                                            </a>
                                        </span>
      
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="forumPostCount">
                                    Replies: @post.RepliesCount
                                </div>
                            </td>
                            <td>
                                <div class="postDate">
                                    @post.DatePosted
                                </div>
                            </td>
                        </tr>

                    }
                </tbody>

            </table>

        }
        else
        {
            <div class="noPosts">
                <i class="material-icons md-72">
                    question_answer
                </i>

                <h3>
                    It looks like there are no posts to be found!
                </h3>
            </div>

        }
    </div>
</div>

@section Scripts {
    <script>
        function clearThis(target) {
            target.value = "";

        }
    </script>
}